//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.11 at 05:05:40 PM CET 
//


package hr.zaba.sova;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the hr.zaba.sova package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _GetTest_QNAME = new QName("http://controller.web.SOVAServices.zaba.hr/", "getTest");
    private final static QName _GetTestResponse_QNAME = new QName("http://controller.web.SOVAServices.zaba.hr/", "getTestResponse");
    private final static QName _WSFunkcijaPO_QNAME = new QName("http://controller.web.SOVAServices.zaba.hr/", "wSFunkcijaPO");
    private final static QName _WSFunkcijaPOResponse_QNAME = new QName("http://controller.web.SOVAServices.zaba.hr/", "wSFunkcijaPOResponse");
    private final static QName _WSKorisnikAplikacija_QNAME = new QName("http://controller.web.SOVAServices.zaba.hr/", "wSKorisnikAplikacija");
    private final static QName _WSKorisnikAplikacijaResponse_QNAME = new QName("http://controller.web.SOVAServices.zaba.hr/", "wSKorisnikAplikacijaResponse");
    private final static QName _WSKorisnikAutorizacija_QNAME = new QName("http://controller.web.SOVAServices.zaba.hr/", "wSKorisnikAutorizacija");
    private final static QName _WSKorisnikAutorizacijaResponse_QNAME = new QName("http://controller.web.SOVAServices.zaba.hr/", "wSKorisnikAutorizacijaResponse");
    private final static QName _WSKorisnikPOSifra_QNAME = new QName("http://controller.web.SOVAServices.zaba.hr/", "wSKorisnikPOSifra");
    private final static QName _WSKorisnikPOSifraResponse_QNAME = new QName("http://controller.web.SOVAServices.zaba.hr/", "wSKorisnikPOSifraResponse");
    private final static QName _WsAplikativneAkcije_QNAME = new QName("http://controller.web.SOVAServices.zaba.hr/", "wsAplikativneAkcije");
    private final static QName _WsAplikativneAkcijePO_QNAME = new QName("http://controller.web.SOVAServices.zaba.hr/", "wsAplikativneAkcijePO");
    private final static QName _WsAplikativneAkcijePOResponse_QNAME = new QName("http://controller.web.SOVAServices.zaba.hr/", "wsAplikativneAkcijePOResponse");
    private final static QName _WsAplikativneAkcijeResponse_QNAME = new QName("http://controller.web.SOVAServices.zaba.hr/", "wsAplikativneAkcijeResponse");
    private final static QName _WsKorisnikAutorizacijaPO_QNAME = new QName("http://controller.web.SOVAServices.zaba.hr/", "wsKorisnikAutorizacijaPO");
    private final static QName _WsKorisnikAutorizacijaPOResponse_QNAME = new QName("http://controller.web.SOVAServices.zaba.hr/", "wsKorisnikAutorizacijaPOResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: hr.zaba.sova
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetTest }
     * 
     */
    public GetTest createGetTest() {
        return new GetTest();
    }

    /**
     * Create an instance of {@link GetTestResponse }
     * 
     */
    public GetTestResponse createGetTestResponse() {
        return new GetTestResponse();
    }

    /**
     * Create an instance of {@link WSFunkcijaPO }
     * 
     */
    public WSFunkcijaPO createWSFunkcijaPO() {
        return new WSFunkcijaPO();
    }

    /**
     * Create an instance of {@link WSFunkcijaPOResponse }
     * 
     */
    public WSFunkcijaPOResponse createWSFunkcijaPOResponse() {
        return new WSFunkcijaPOResponse();
    }

    /**
     * Create an instance of {@link WSKorisnikAplikacija }
     * 
     */
    public WSKorisnikAplikacija createWSKorisnikAplikacija() {
        return new WSKorisnikAplikacija();
    }

    /**
     * Create an instance of {@link WSKorisnikAplikacijaResponse }
     * 
     */
    public WSKorisnikAplikacijaResponse createWSKorisnikAplikacijaResponse() {
        return new WSKorisnikAplikacijaResponse();
    }

    /**
     * Create an instance of {@link WSKorisnikAutorizacija }
     * 
     */
    public WSKorisnikAutorizacija createWSKorisnikAutorizacija() {
        return new WSKorisnikAutorizacija();
    }

    /**
     * Create an instance of {@link WSKorisnikAutorizacijaResponse }
     * 
     */
    public WSKorisnikAutorizacijaResponse createWSKorisnikAutorizacijaResponse() {
        return new WSKorisnikAutorizacijaResponse();
    }

    /**
     * Create an instance of {@link WSKorisnikPOSifra }
     * 
     */
    public WSKorisnikPOSifra createWSKorisnikPOSifra() {
        return new WSKorisnikPOSifra();
    }

    /**
     * Create an instance of {@link WSKorisnikPOSifraResponse }
     * 
     */
    public WSKorisnikPOSifraResponse createWSKorisnikPOSifraResponse() {
        return new WSKorisnikPOSifraResponse();
    }

    /**
     * Create an instance of {@link WsAplikativneAkcije }
     * 
     */
    public WsAplikativneAkcije createWsAplikativneAkcije() {
        return new WsAplikativneAkcije();
    }

    /**
     * Create an instance of {@link WsAplikativneAkcijePO }
     * 
     */
    public WsAplikativneAkcijePO createWsAplikativneAkcijePO() {
        return new WsAplikativneAkcijePO();
    }

    /**
     * Create an instance of {@link WsAplikativneAkcijePOResponse }
     * 
     */
    public WsAplikativneAkcijePOResponse createWsAplikativneAkcijePOResponse() {
        return new WsAplikativneAkcijePOResponse();
    }

    /**
     * Create an instance of {@link WsAplikativneAkcijeResponse }
     * 
     */
    public WsAplikativneAkcijeResponse createWsAplikativneAkcijeResponse() {
        return new WsAplikativneAkcijeResponse();
    }

    /**
     * Create an instance of {@link WsKorisnikAutorizacijaPO }
     * 
     */
    public WsKorisnikAutorizacijaPO createWsKorisnikAutorizacijaPO() {
        return new WsKorisnikAutorizacijaPO();
    }

    /**
     * Create an instance of {@link WsKorisnikAutorizacijaPOResponse }
     * 
     */
    public WsKorisnikAutorizacijaPOResponse createWsKorisnikAutorizacijaPOResponse() {
        return new WsKorisnikAutorizacijaPOResponse();
    }

    /**
     * Create an instance of {@link WsKorisnikPOSifraData }
     * 
     */
    public WsKorisnikPOSifraData createWsKorisnikPOSifraData() {
        return new WsKorisnikPOSifraData();
    }

    /**
     * Create an instance of {@link WsKorisnikAutorizacijaPOData }
     * 
     */
    public WsKorisnikAutorizacijaPOData createWsKorisnikAutorizacijaPOData() {
        return new WsKorisnikAutorizacijaPOData();
    }

    /**
     * Create an instance of {@link WsKorinikAutorizacijaoData }
     * 
     */
    public WsKorinikAutorizacijaoData createWsKorinikAutorizacijaoData() {
        return new WsKorinikAutorizacijaoData();
    }

    /**
     * Create an instance of {@link WsAplikativneAkcijePOData }
     * 
     */
    public WsAplikativneAkcijePOData createWsAplikativneAkcijePOData() {
        return new WsAplikativneAkcijePOData();
    }

    /**
     * Create an instance of {@link WsFunkcijaPoParametri }
     * 
     */
    public WsFunkcijaPoParametri createWsFunkcijaPoParametri() {
        return new WsFunkcijaPoParametri();
    }

    /**
     * Create an instance of {@link WsZaposlenikPOData }
     * 
     */
    public WsZaposlenikPOData createWsZaposlenikPOData() {
        return new WsZaposlenikPOData();
    }

    /**
     * Create an instance of {@link WsAplikativneAkcijeData }
     * 
     */
    public WsAplikativneAkcijeData createWsAplikativneAkcijeData() {
        return new WsAplikativneAkcijeData();
    }

    /**
     * Create an instance of {@link WsKorisnikAplikacijaData }
     * 
     */
    public WsKorisnikAplikacijaData createWsKorisnikAplikacijaData() {
        return new WsKorisnikAplikacijaData();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetTest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://controller.web.SOVAServices.zaba.hr/", name = "getTest")
    public JAXBElement<GetTest> createGetTest(GetTest value) {
        return new JAXBElement<GetTest>(_GetTest_QNAME, GetTest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetTestResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://controller.web.SOVAServices.zaba.hr/", name = "getTestResponse")
    public JAXBElement<GetTestResponse> createGetTestResponse(GetTestResponse value) {
        return new JAXBElement<GetTestResponse>(_GetTestResponse_QNAME, GetTestResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link WSFunkcijaPO }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://controller.web.SOVAServices.zaba.hr/", name = "wSFunkcijaPO")
    public JAXBElement<WSFunkcijaPO> createWSFunkcijaPO(WSFunkcijaPO value) {
        return new JAXBElement<WSFunkcijaPO>(_WSFunkcijaPO_QNAME, WSFunkcijaPO.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link WSFunkcijaPOResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://controller.web.SOVAServices.zaba.hr/", name = "wSFunkcijaPOResponse")
    public JAXBElement<WSFunkcijaPOResponse> createWSFunkcijaPOResponse(WSFunkcijaPOResponse value) {
        return new JAXBElement<WSFunkcijaPOResponse>(_WSFunkcijaPOResponse_QNAME, WSFunkcijaPOResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link WSKorisnikAplikacija }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://controller.web.SOVAServices.zaba.hr/", name = "wSKorisnikAplikacija")
    public JAXBElement<WSKorisnikAplikacija> createWSKorisnikAplikacija(WSKorisnikAplikacija value) {
        return new JAXBElement<WSKorisnikAplikacija>(_WSKorisnikAplikacija_QNAME, WSKorisnikAplikacija.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link WSKorisnikAplikacijaResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://controller.web.SOVAServices.zaba.hr/", name = "wSKorisnikAplikacijaResponse")
    public JAXBElement<WSKorisnikAplikacijaResponse> createWSKorisnikAplikacijaResponse(WSKorisnikAplikacijaResponse value) {
        return new JAXBElement<WSKorisnikAplikacijaResponse>(_WSKorisnikAplikacijaResponse_QNAME, WSKorisnikAplikacijaResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link WSKorisnikAutorizacija }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://controller.web.SOVAServices.zaba.hr/", name = "wSKorisnikAutorizacija")
    public JAXBElement<WSKorisnikAutorizacija> createWSKorisnikAutorizacija(WSKorisnikAutorizacija value) {
        return new JAXBElement<WSKorisnikAutorizacija>(_WSKorisnikAutorizacija_QNAME, WSKorisnikAutorizacija.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link WSKorisnikAutorizacijaResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://controller.web.SOVAServices.zaba.hr/", name = "wSKorisnikAutorizacijaResponse")
    public JAXBElement<WSKorisnikAutorizacijaResponse> createWSKorisnikAutorizacijaResponse(WSKorisnikAutorizacijaResponse value) {
        return new JAXBElement<WSKorisnikAutorizacijaResponse>(_WSKorisnikAutorizacijaResponse_QNAME, WSKorisnikAutorizacijaResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link WSKorisnikPOSifra }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://controller.web.SOVAServices.zaba.hr/", name = "wSKorisnikPOSifra")
    public JAXBElement<WSKorisnikPOSifra> createWSKorisnikPOSifra(WSKorisnikPOSifra value) {
        return new JAXBElement<WSKorisnikPOSifra>(_WSKorisnikPOSifra_QNAME, WSKorisnikPOSifra.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link WSKorisnikPOSifraResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://controller.web.SOVAServices.zaba.hr/", name = "wSKorisnikPOSifraResponse")
    public JAXBElement<WSKorisnikPOSifraResponse> createWSKorisnikPOSifraResponse(WSKorisnikPOSifraResponse value) {
        return new JAXBElement<WSKorisnikPOSifraResponse>(_WSKorisnikPOSifraResponse_QNAME, WSKorisnikPOSifraResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link WsAplikativneAkcije }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://controller.web.SOVAServices.zaba.hr/", name = "wsAplikativneAkcije")
    public JAXBElement<WsAplikativneAkcije> createWsAplikativneAkcije(WsAplikativneAkcije value) {
        return new JAXBElement<WsAplikativneAkcije>(_WsAplikativneAkcije_QNAME, WsAplikativneAkcije.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link WsAplikativneAkcijePO }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://controller.web.SOVAServices.zaba.hr/", name = "wsAplikativneAkcijePO")
    public JAXBElement<WsAplikativneAkcijePO> createWsAplikativneAkcijePO(WsAplikativneAkcijePO value) {
        return new JAXBElement<WsAplikativneAkcijePO>(_WsAplikativneAkcijePO_QNAME, WsAplikativneAkcijePO.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link WsAplikativneAkcijePOResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://controller.web.SOVAServices.zaba.hr/", name = "wsAplikativneAkcijePOResponse")
    public JAXBElement<WsAplikativneAkcijePOResponse> createWsAplikativneAkcijePOResponse(WsAplikativneAkcijePOResponse value) {
        return new JAXBElement<WsAplikativneAkcijePOResponse>(_WsAplikativneAkcijePOResponse_QNAME, WsAplikativneAkcijePOResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link WsAplikativneAkcijeResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://controller.web.SOVAServices.zaba.hr/", name = "wsAplikativneAkcijeResponse")
    public JAXBElement<WsAplikativneAkcijeResponse> createWsAplikativneAkcijeResponse(WsAplikativneAkcijeResponse value) {
        return new JAXBElement<WsAplikativneAkcijeResponse>(_WsAplikativneAkcijeResponse_QNAME, WsAplikativneAkcijeResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link WsKorisnikAutorizacijaPO }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://controller.web.SOVAServices.zaba.hr/", name = "wsKorisnikAutorizacijaPO")
    public JAXBElement<WsKorisnikAutorizacijaPO> createWsKorisnikAutorizacijaPO(WsKorisnikAutorizacijaPO value) {
        return new JAXBElement<WsKorisnikAutorizacijaPO>(_WsKorisnikAutorizacijaPO_QNAME, WsKorisnikAutorizacijaPO.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link WsKorisnikAutorizacijaPOResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://controller.web.SOVAServices.zaba.hr/", name = "wsKorisnikAutorizacijaPOResponse")
    public JAXBElement<WsKorisnikAutorizacijaPOResponse> createWsKorisnikAutorizacijaPOResponse(WsKorisnikAutorizacijaPOResponse value) {
        return new JAXBElement<WsKorisnikAutorizacijaPOResponse>(_WsKorisnikAutorizacijaPOResponse_QNAME, WsKorisnikAutorizacijaPOResponse.class, null, value);
    }

}
