//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.11 at 05:05:40 PM CET 
//


package hr.zaba.sova;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for wsAplikativneAkcijeData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="wsAplikativneAkcijeData"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="sifraAkcije" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="tipAkcije" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "wsAplikativneAkcijeData", propOrder = {
    "sifraAkcije",
    "tipAkcije"
})
public class WsAplikativneAkcijeData {

    protected String sifraAkcije;
    protected String tipAkcije;

    /**
     * Gets the value of the sifraAkcije property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSifraAkcije() {
        return sifraAkcije;
    }

    /**
     * Sets the value of the sifraAkcije property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSifraAkcije(String value) {
        this.sifraAkcije = value;
    }

    /**
     * Gets the value of the tipAkcije property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipAkcije() {
        return tipAkcije;
    }

    /**
     * Sets the value of the tipAkcije property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipAkcije(String value) {
        this.tipAkcije = value;
    }

}
