//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.10 at 09:44:29 PM CET 
//


package hr.zaba.sova;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for wsFunkcijaPoParametri complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="wsFunkcijaPoParametri"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="strTip" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="strVrijednostPO" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "wsFunkcijaPoParametri", propOrder = {
    "strTip",
    "strVrijednostPO"
})
public class WsFunkcijaPoParametri {

    protected String strTip;
    protected String strVrijednostPO;

    /**
     * Gets the value of the strTip property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStrTip() {
        return strTip;
    }

    /**
     * Sets the value of the strTip property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStrTip(String value) {
        this.strTip = value;
    }

    /**
     * Gets the value of the strVrijednostPO property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStrVrijednostPO() {
        return strVrijednostPO;
    }

    /**
     * Sets the value of the strVrijednostPO property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStrVrijednostPO(String value) {
        this.strVrijednostPO = value;
    }

}
