//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.11 at 05:05:40 PM CET 
//


package hr.zaba.sova;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for wsKorinikAutorizacijaoData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="wsKorinikAutorizacijaoData"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="aplikacija" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="funkcija" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "wsKorinikAutorizacijaoData", propOrder = {
    "aplikacija",
    "funkcija"
})
public class WsKorinikAutorizacijaoData {

    protected String aplikacija;
    protected String funkcija;

    /**
     * Gets the value of the aplikacija property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAplikacija() {
        return aplikacija;
    }

    /**
     * Sets the value of the aplikacija property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAplikacija(String value) {
        this.aplikacija = value;
    }

    /**
     * Gets the value of the funkcija property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFunkcija() {
        return funkcija;
    }

    /**
     * Sets the value of the funkcija property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFunkcija(String value) {
        this.funkcija = value;
    }

}
