//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.17 at 11:06:37 AM CET 
//


package hr.zaba.session;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the hr.zaba.session package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _CreateAuthIdRequest_QNAME = new QName("http://pfm.assecosee.hr/sessionTransferService/1.0", "CreateAuthIdRequest");
    private final static QName _CreateAuthIdResponse_QNAME = new QName("http://pfm.assecosee.hr/sessionTransferService/1.0", "CreateAuthIdResponse");
    private final static QName _CheckAuthIdRequest_QNAME = new QName("http://pfm.assecosee.hr/sessionTransferService/1.0", "CheckAuthIdRequest");
    private final static QName _CheckAuthIdResponse_QNAME = new QName("http://pfm.assecosee.hr/sessionTransferService/1.0", "CheckAuthIdResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: hr.zaba.session
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CreateAuthIdRequestType }
     * 
     */
    public CreateAuthIdRequestType createCreateAuthIdRequestType() {
        return new CreateAuthIdRequestType();
    }

    /**
     * Create an instance of {@link CreateAuthIdResponseType }
     * 
     */
    public CreateAuthIdResponseType createCreateAuthIdResponseType() {
        return new CreateAuthIdResponseType();
    }

    /**
     * Create an instance of {@link CheckAuthIdRequestType }
     * 
     */
    public CheckAuthIdRequestType createCheckAuthIdRequestType() {
        return new CheckAuthIdRequestType();
    }

    /**
     * Create an instance of {@link CheckAuthIdResponseType }
     * 
     */
    public CheckAuthIdResponseType createCheckAuthIdResponseType() {
        return new CheckAuthIdResponseType();
    }

    /**
     * Create an instance of {@link ServiceErrorType }
     * 
     */
    public ServiceErrorType createServiceErrorType() {
        return new ServiceErrorType();
    }

    /**
     * Create an instance of {@link ArrayOfServiceErrorType }
     * 
     */
    public ArrayOfServiceErrorType createArrayOfServiceErrorType() {
        return new ArrayOfServiceErrorType();
    }

    /**
     * Create an instance of {@link ResponseBaseType }
     * 
     */
    public ResponseBaseType createResponseBaseType() {
        return new ResponseBaseType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreateAuthIdRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://pfm.assecosee.hr/sessionTransferService/1.0", name = "CreateAuthIdRequest")
    public JAXBElement<CreateAuthIdRequestType> createCreateAuthIdRequest(CreateAuthIdRequestType value) {
        return new JAXBElement<CreateAuthIdRequestType>(_CreateAuthIdRequest_QNAME, CreateAuthIdRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreateAuthIdResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://pfm.assecosee.hr/sessionTransferService/1.0", name = "CreateAuthIdResponse")
    public JAXBElement<CreateAuthIdResponseType> createCreateAuthIdResponse(CreateAuthIdResponseType value) {
        return new JAXBElement<CreateAuthIdResponseType>(_CreateAuthIdResponse_QNAME, CreateAuthIdResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CheckAuthIdRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://pfm.assecosee.hr/sessionTransferService/1.0", name = "CheckAuthIdRequest")
    public JAXBElement<CheckAuthIdRequestType> createCheckAuthIdRequest(CheckAuthIdRequestType value) {
        return new JAXBElement<CheckAuthIdRequestType>(_CheckAuthIdRequest_QNAME, CheckAuthIdRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CheckAuthIdResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://pfm.assecosee.hr/sessionTransferService/1.0", name = "CheckAuthIdResponse")
    public JAXBElement<CheckAuthIdResponseType> createCheckAuthIdResponse(CheckAuthIdResponseType value) {
        return new JAXBElement<CheckAuthIdResponseType>(_CheckAuthIdResponse_QNAME, CheckAuthIdResponseType.class, null, value);
    }

}
